### ISSUE TITLE
Some Markdown formatting symbols * or _ in inline LaTeX formulas may cause rendering errors

### ISSUE THREAD

**Issue by lethefrost** [scruel/tampermonkey-scripts#12] opened 2023-04-07 20:41 UTC
On ChatGPT's web interface, if such formulas appear in the form of `{x}_a` and `y_{b}` (where `x, y, a, b` can be any elements, they can be either the same or different, the key point is that there are two `_` in the same paragraph, and, the one character just immediately before the former `_` and the one after the latter `_`, are symbols instead of numbers/letters. The same goes for `*`), the `_`s will be first consumed as the italic formatting character of Markdown, causing unwanted rendering results.

I made the following table to demonstrate some test cases (I suddenly found that GitHub also has this problem? I am now confused about whether this is a bug or a feature... Are they using the same rendering module? I just tried some other Markdown toke taking apps such as Obsidian, Logseq, and so on, and pandoc for exporting Markdown to PDF, and they all render correctly... For now I only found GitHub and ChatGPT have this issue.) 

| Source Text                             | Rendered Result                       | Explanation                                                                                                                                                         |
| --------------------------------------- | ------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `$x_a$ and $y_b$`                       | $x_a$ and $y_b$                       | If rendered correctly                                                                                                                                               |
| `${x}_a$ and $y_{b}$`                   | ${x}_a$ and $y_{b}$                   | Being treated as italic formatter                                                                                                                                   |
| `${x}_{a}$ and ${y}_{b}$`               | ${x}_{a}$ and ${y}_{b}$               | As long as the characters before the first `_` and after the second `_` are symbols, it will cause this bug, and it doesn't matter whether it is a symbol elsewhere |
| `${x}_a = y_{b}$`                       | ${x}_a = y_{b}$                       | Even if it is not two separated inline formulas in the same line but in the same formula, it will be treated as italic                                              |
| `$x^@_i = y_@$`                         | $x^@_i = y_@$                         | It doesn't have to be characters like `{}`, as long as the adjacent characters are not a letter/number, it will cause this bug                                      |
| `$x^2_i = y_2$`                         | $x^2_i = y_2$                         | If the adjacencies are numbers, it will be rendered correctly                                                                                                                    |
| `${x}^{*} = {y}^{*}$`                   | ${x}^{*} = {y}^{*}$                   | Consuming `*` and becoming italic                                                                                                                                   |
| `$\mathbf{w}_t$ and $\mathbf{w}_{t+1}$` | $\mathbf{w}_t$ and $\mathbf{w}_{t+1}$ | Such formulas are quite common in gradient descent and other fields, but cannot be rendered correctly…                                                              |

Screenshots: 
- This is what GitHub does: <img width="850" alt="image" src="https://user-images.githubusercontent.com/47198693/230673880-06488b61-6fea-4bb8-af72-42c130c32142.png">
- This is what ChatGPT render the table: <img width="715" alt="image" src="https://user-images.githubusercontent.com/47198693/230674134-04624473-eb0f-4caf-a463-0895e54de6dc.png">
- This is what it shows with your LaTeX renderer script: <img width="714" alt="image" src="https://user-images.githubusercontent.com/47198693/230674382-99b0e5e5-a495-4482-a562-1ab478d4fe31.png">

Do you have any idea what this bug or feature is caused by? Do GitHub and ChatGPT share the same module rendering Markdown? But why wasn't ChatGPT originally able to render the inline formulas? I am getting really confused here.

I am wondering would it be possible for you to catch the `_` characters in the source text and render it by MathJax before they are consumed by the Markdown renderer. Looks like the source text of GPT generated response can be obtained by some means. For example, the repo [chatgpt-exporter](https://github.com/pionxzh/chatgpt-exporter) does so. 

Hope we can figure this out. Thank you so much! I greatly appreciate your work, and it indeed helped me a lot. ❤️

**Comment by scruel** [comment] 2023-04-08 06:15
Hi, thanks for posting this issue with well explanation, after checking and reproduce the cases you provided, I already know why this happened, I will try to fix this.
The reason why chatgpt-exporter won't have this issue is because it will fetch the raw content from API directly, rather than parse the HTML content which polluted by other renderers.

**Comment by scruel** [comment] 2023-04-08 09:25
Temporary fixed in 0.5.8.

**Comment by scruel** [comment] 2023-04-08 09:52
We reversed the HTML `em` tag back to `_` only, so it will lead to another issue:
Because the Markdown render won't let us be possible to know the original symbol used to render the `em` tag is either `_` or `*`, so for the formula `${x}^{*} = {y}^{*}$`, the script won't be able to typeset it correctly.
Will try to fix this also.

**Comment by lethefrost** [comment] 2023-04-08 22:24
> Hi, thanks for posting this issue with well explanation, after checking and reproduce the cases you provided, I already know why this happened, I will try to fix this. The reason why chatgpt-exporter won't have this issue is because it will fetch the raw content from API directly, rather than parse the HTML content which polluted by other renderers.

Hi scruel, thank you!! God. You are really amazing! How fast you are identifying the issue. I don't understand why at all, and wonder if you would mind taking some time to explain to me why ChatGPT and GitHub are both having issues like this? Really appreciate your quick response and fix. It's so impressive! 

Also, thank you for also recognizing the `*` problem for the temporary solution! I am thinking of some unique syntax for `_` might help distinguish the cases of `*` or `_`. For example, if the `<em>` tags matches the following cases, they cannot be `_` originally (and i.e. must be `*`), because of the syntactic rules of $\LaTeX$, 
- `$<em>` or `<em>$` - immediately next to the `$` boundaries at either the beginning or end of the inline formula
- `[_^][{}]*<em>` or `<em>[{}]*[_^]` - following or followed by either another `_` or `^`, with only (potentially) `{` or `}` in between
- ... Possibly more cases that can help exclude and eliminate `_`?
- Also just by the way, as far as I know, em tags are not nested, so it might be helpful to think this way: Once a `<em>` or `</em>` is determined, the nearest one paired with it can be determined to be the same character.

Thank you again for your work! Really appreciate it. Hope I am helping 😊. I just found a new bug with the 0.5.8 release and I will raise a new issue for this.

**Comment by scruel** [comment] 2023-04-09 05:13
@lethefrost
For GitHub, I can't be sure the reason why caused this.
The problem here for ChatGPT page, is caused by the wrong rendering order, like you said before, we should first typeset LaTeX formulas, then render Markdown formats, but as a script (without injecting), it can only do it at the end.
Your provided cases are helpful, I will consider them while I am fixing this.
Currently, I can fetch the raw content for matching to confirm the original symbol, however, I think I will have to reverse some parts of HTML back to Markdown to do the match, and this "reverse" processing also will cause some problems, so for fixing this, I will need some time.

**Comment by scruel** [comment] 2023-04-11 06:59
Fixed in 0.6.0.

**Closed as completed by scruel** 2023-04-11 06:59 UTC
